# Workflow de CI usando Docker autosuficiente
# Ejecuta TODAS las pruebas dentro del contenedor Docker.
# La imagen ya incluye: Java 11, Maven, Chrome, Firefox y GeckoDriver.

name: Run Tests Selenium Java

on:
  push:
    branches:
      - main
    paths:
      - '**/*.java'
      - '**/*.xml'
      - '**/*.feature'
      - 'pom.xml'
      - 'Dockerfile'

  pull_request:
    branches:
      - main
    paths:
      - '**/*.java'
      - '**/*.xml'
      - '**/*.feature'
      - 'pom.xml'
      - 'Dockerfile'


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Construir imagen Docker
      - name: Build Docker image
        run: docker build -t selenium-tests .

      # 3. Ejecutar pruebas dentro del contenedor
      - name: Run tests
        run: docker run --rm selenium-tests

      # 4. Guardar reporte Allure (opcional)
      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: |
            target/allure-results
            target/allure-report
